### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by morangeous** [ExpoSEJS/z3javascript#1]
Hi, when I tried to run the command:

> expoSE replay

I get the following error:
`/home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: node: undefined symbol: Z3_global_param_set
    at DynamicLibrary.get (/home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (/home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/ffi/lib/library.js:47:28)
    at _default (/home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/z3javascript/bin/package.js:762:28)
    at Object.<anonymous> (/home/moran/workspace/js-analysis/ExpoSE-master/Analyser/node_modules/z3javascript/bin/Z3Loader.js:17:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
`
Could you please give me a hand ?

**Comment by morangeous** [comment]
@jawline

**Comment by jawline** [comment]
This is a bug with ExpoSE not z3javascript, I've added a patch. It will be merged once tests pass. Please re-raise on ExpoSE
